
import { Account, AccountType } from './types';

export const INITIAL_ACCOUNTS: Account[] = [
  { id: '1', code: '1101', name: 'الصندوق', type: AccountType.ASSET, balance: 0 },
  { id: '2', code: '1102', name: 'البنك', type: AccountType.ASSET, balance: 0 },
  { id: '3', code: '1201', name: 'المخزون', type: AccountType.ASSET, balance: 0 },
  { id: '4', code: '1301', name: 'السيارات', type: AccountType.ASSET, balance: 0 },
  { id: '5', code: '2101', name: 'الموردين', type: AccountType.LIABILITY, balance: 0 },
  { id: '6', code: '2201', name: 'قروض قصيرة الأجل', type: AccountType.LIABILITY, balance: 0 },
  { id: '7', code: '3101', name: 'رأس المال', type: AccountType.EQUITY, balance: 0 },
  { id: '8', code: '4101', name: 'مبيعات المنتجات', type: AccountType.INCOME, balance: 0 },
  { id: '9', code: '4102', name: 'إيرادات خدمات', type: AccountType.INCOME, balance: 0 },
  { id: '10', code: '5101', name: 'مصاريف رواتب', type: AccountType.EXPENSE, balance: 0 },
  { id: '11', code: '5102', name: 'مصاريف إيجار', type: AccountType.EXPENSE, balance: 0 },
  { id: '12', code: '5103', name: 'مصاريف كهرباء ومياه', type: AccountType.EXPENSE, balance: 0 },
  { id: '13', code: '5201', name: 'مشتريات بضاعة (خام)', type: AccountType.EXPENSE, balance: 0 },
  { id: '14', code: '5202', name: 'تكلفة البضاعة المباعة', type: AccountType.EXPENSE, balance: 0 },
];

export const TRANSLATIONS = {
  ar: {
    dashboard: 'الرئيسية',
    sales: 'المبيعات',
    purchases: 'المشتريات',
    inventory: 'المخزون',
    journal: 'القيود',
    accounts: 'دليل الحسابات',
    incomeStatement: 'قائمة الدخل',
    balanceSheet: 'المركز المالي',
    inventoryReport: 'تقرير المخزون',
    settings: 'الإعدادات',
    companyNameLabel: 'اسم الشركة',
    languageLabel: 'اللغة',
    themeLabel: 'المظهر',
    currencyLabel: 'العملة',
    saveSettings: 'حفظ الإعدادات',
    light: 'فاتح',
    dark: 'داكن',
    totalAssets: 'إجمالي الأصول',
    totalLiabilities: 'إجمالي الالتزامات',
    netProfit: 'صافي الربح',
    expenses: 'المصروفات',
    statusConnected: 'متصل',
    financialManager: 'المدير المالي',
    appTitle: 'نظام المحاسب الذكي',
  },
  en: {
    dashboard: 'Dashboard',
    sales: 'Sales',
    purchases: 'Purchases',
    inventory: 'Inventory',
    journal: 'Journal',
    accounts: 'Chart of Accounts',
    incomeStatement: 'Income Statement',
    balanceSheet: 'Balance Sheet',
    inventoryReport: 'Inventory Report',
    settings: 'Settings',
    companyNameLabel: 'Company Name',
    languageLabel: 'Language',
    themeLabel: 'Theme',
    currencyLabel: 'Currency',
    saveSettings: 'Save Settings',
    light: 'Light',
    dark: 'Dark',
    totalAssets: 'Total Assets',
    totalLiabilities: 'Total Liabilities',
    netProfit: 'Net Profit',
    expenses: 'Expenses',
    statusConnected: 'Online',
    financialManager: 'Financial Manager',
    appTitle: 'Smart Accountant System',
  }
};
